In [1]:
import numpy as np

In [2]:
mylist = [1,2,3,4,5]
data = np.array(mylist)

In [4]:
data

array([1, 2, 3, 4, 5])

In [7]:
one_vect = np.ones(4)
one_vect

array([ 1.,  1.,  1.,  1.])

In [8]:
mul_vect = np.ones((2,3))
mul_vect

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [9]:
zero_vect = np.zeros(5)
zero_vect

array([ 0.,  0.,  0.,  0.,  0.])

In [15]:
empty_vector = np.empty(5)
empty_vector

array([ 0.,  0.,  0.,  0.,  0.])

In [16]:
random_vector=np.random.random(10)
random_vector

array([ 0.86069627,  0.8815908 ,  0.7087477 ,  0.18938337,  0.13659254,
        0.01206012,  0.05433602,  0.20878734,  0.3860075 ,  0.43502745])

In [17]:
fib_indices=np.array([0,1,3,5])

In [18]:
random_vector[fib_indices]

array([ 0.86069627,  0.8815908 ,  0.18938337,  0.01206012])

In [19]:
fib_indices

array([0, 1, 3, 5])

In [22]:
a=[0,1,3,4]
a

[0, 1, 3, 4]

In [21]:
random_vector[a]

array([ 0.86069627,  0.8815908 ,  0.18938337,  0.13659254])